libpkgconf: fragment: Support platform that doesn't support nl_langinfo_l
On NetBSD, nl_langinfo_l isn't defined, so I was getting this error:
```
  ../libpkgconf/fragment.c:686:26: error: implicit declaration of function ‘nl_langinfo_l’; did you mean ‘nl_langinfo’? [-Werror=implicit-function-declaration]
    686 |    const char *codeset = nl_langinfo_l(CODESET, loc);
        |                          ^~~~~~~~~~~~~
        |                          nl_langinfo
```

On platforms that don't support nl_langinfo_l, let's use nl_langinfo instead. This isn't perfect because we need to call setlocale, which changes the locale for the whole process. For libraries that use libpkgconf, this can be a problem, but it doesn't seem possible to query the locale without affecting the process when nl_langinfo_l isn't available.

Signed-off-by: moi15moi <moi15moismokerlolilol@gmail.com>